// Code generated by mockery v2.50.0. DO NOT EDIT.

package mocks

import (
	context "context"
	contractv1 "tinvest-go/internal/pb"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"
)

// SignalsAPIMock is an autogenerated mock type for the SignalsAPIMock type
type SignalsAPIMock struct {
	mock.Mock
}

type SignalsAPIMock_Expecter struct {
	mock *mock.Mock
}

func (_m *SignalsAPIMock) EXPECT() *SignalsAPIMock_Expecter {
	return &SignalsAPIMock_Expecter{mock: &_m.Mock}
}

// GetSignals provides a mock function with given fields: ctx, in, opts
func (_m *SignalsAPIMock) GetSignals(ctx context.Context, in *contractv1.GetSignalsRequest, opts ...grpc.CallOption) (*contractv1.GetSignalsResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetSignals")
	}

	var r0 *contractv1.GetSignalsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *contractv1.GetSignalsRequest, ...grpc.CallOption) (*contractv1.GetSignalsResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *contractv1.GetSignalsRequest, ...grpc.CallOption) *contractv1.GetSignalsResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*contractv1.GetSignalsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *contractv1.GetSignalsRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SignalsAPIMock_GetSignals_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSignals'
type SignalsAPIMock_GetSignals_Call struct {
	*mock.Call
}

// GetSignals is a helper method to define mock.On call
//   - ctx context.Context
//   - in *contractv1.GetSignalsRequest
//   - opts ...grpc.CallOption
func (_e *SignalsAPIMock_Expecter) GetSignals(ctx interface{}, in interface{}, opts ...interface{}) *SignalsAPIMock_GetSignals_Call {
	return &SignalsAPIMock_GetSignals_Call{Call: _e.mock.On("GetSignals",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *SignalsAPIMock_GetSignals_Call) Run(run func(ctx context.Context, in *contractv1.GetSignalsRequest, opts ...grpc.CallOption)) *SignalsAPIMock_GetSignals_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*contractv1.GetSignalsRequest), variadicArgs...)
	})
	return _c
}

func (_c *SignalsAPIMock_GetSignals_Call) Return(_a0 *contractv1.GetSignalsResponse, _a1 error) *SignalsAPIMock_GetSignals_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SignalsAPIMock_GetSignals_Call) RunAndReturn(run func(context.Context, *contractv1.GetSignalsRequest, ...grpc.CallOption) (*contractv1.GetSignalsResponse, error)) *SignalsAPIMock_GetSignals_Call {
	_c.Call.Return(run)
	return _c
}

// GetStrategies provides a mock function with given fields: ctx, in, opts
func (_m *SignalsAPIMock) GetStrategies(ctx context.Context, in *contractv1.GetStrategiesRequest, opts ...grpc.CallOption) (*contractv1.GetStrategiesResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetStrategies")
	}

	var r0 *contractv1.GetStrategiesResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *contractv1.GetStrategiesRequest, ...grpc.CallOption) (*contractv1.GetStrategiesResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *contractv1.GetStrategiesRequest, ...grpc.CallOption) *contractv1.GetStrategiesResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*contractv1.GetStrategiesResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *contractv1.GetStrategiesRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SignalsAPIMock_GetStrategies_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStrategies'
type SignalsAPIMock_GetStrategies_Call struct {
	*mock.Call
}

// GetStrategies is a helper method to define mock.On call
//   - ctx context.Context
//   - in *contractv1.GetStrategiesRequest
//   - opts ...grpc.CallOption
func (_e *SignalsAPIMock_Expecter) GetStrategies(ctx interface{}, in interface{}, opts ...interface{}) *SignalsAPIMock_GetStrategies_Call {
	return &SignalsAPIMock_GetStrategies_Call{Call: _e.mock.On("GetStrategies",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *SignalsAPIMock_GetStrategies_Call) Run(run func(ctx context.Context, in *contractv1.GetStrategiesRequest, opts ...grpc.CallOption)) *SignalsAPIMock_GetStrategies_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*contractv1.GetStrategiesRequest), variadicArgs...)
	})
	return _c
}

func (_c *SignalsAPIMock_GetStrategies_Call) Return(_a0 *contractv1.GetStrategiesResponse, _a1 error) *SignalsAPIMock_GetStrategies_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SignalsAPIMock_GetStrategies_Call) RunAndReturn(run func(context.Context, *contractv1.GetStrategiesRequest, ...grpc.CallOption) (*contractv1.GetStrategiesResponse, error)) *SignalsAPIMock_GetStrategies_Call {
	_c.Call.Return(run)
	return _c
}

// NewSignalsAPIMock creates a new instance of SignalsAPIMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSignalsAPIMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *SignalsAPIMock {
	mock := &SignalsAPIMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
