run:
  timeout: 10m
  issues-exit-code: 1
  tests: true

output:
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  funlen: #default 60/40
    lines: 245
    statements: 102
  gocyclo:
    min-complexity: 15
  gocognit:
    min-complexity: 15
  revive:
    rules:
      - name: file-header
        disabled: true

linters:
  # disable-all: true
  enable:
    - errcheck
    - goconst
    - goimports
    - gosec
    - govet
    - ineffassign
    - gosimple
    - staticcheck
    - unused
    - revive
    - typecheck
    - copyloopvar
    - prealloc
    - wastedassign
    - unparam
    - funlen
    - gocyclo
    - gocognit
